import type {
  Addon,
  Booking,
  Car,
  DashboardMetrics,
  Location,
} from "./types";

export const LOCATIONS: Location[] = [
  {
    id: "loc-cmn",
    name: "Casablanca Airport (CMN)",
    nameFr: "Aéroport Casablanca (CMN)",
    nameAr: "مطار الدار البيضاء",
    type: "airport",
    code: "CMN",
    city: "Casablanca",
    deliveryFeeMad: 200,
  },
  {
    id: "loc-rak",
    name: "Marrakech Airport (RAK)",
    nameFr: "Aéroport Marrakech (RAK)",
    nameAr: "مطار مراكش",
    type: "airport",
    code: "RAK",
    city: "Marrakech",
    deliveryFeeMad: 250,
  },
  {
    id: "loc-tng",
    name: "Tangier Airport (TNG)",
    nameFr: "Aéroport Tanger (TNG)",
    nameAr: "مطار طنجة",
    type: "airport",
    code: "TNG",
    city: "Tangier",
    deliveryFeeMad: 200,
  },
  {
    id: "loc-aga",
    name: "Agadir Airport (AGA)",
    nameFr: "Aéroport Agadir (AGA)",
    nameAr: "مطار أكادير",
    type: "airport",
    code: "AGA",
    city: "Agadir",
    deliveryFeeMad: 250,
  },
  {
    id: "loc-ndg",
    name: "Nador Airport (NDG)",
    nameFr: "Aéroport Nador (NDG)",
    nameAr: "مطار الناظور",
    type: "airport",
    code: "NDG",
    city: "Nador",
    deliveryFeeMad: 150,
  },
  {
    id: "loc-fez",
    name: "Fès Airport (FEZ)",
    nameFr: "Aéroport Fès (FEZ)",
    nameAr: "مطار فاس",
    type: "airport",
    code: "FEZ",
    city: "Fès",
    deliveryFeeMad: 200,
  },
  {
    id: "loc-driouch",
    name: "LuxuryCar Driouch Agency",
    nameFr: "Agence LuxuryCar Driouch",
    nameAr: "وكالة لوكسري كار الدريوش",
    type: "agency",
    city: "Driouch",
    deliveryFeeMad: 0,
  },
  {
    id: "loc-casa-center",
    name: "Casablanca City Center",
    nameFr: "Centre-ville Casablanca",
    nameAr: "وسط مدينة الدار البيضاء",
    type: "city",
    city: "Casablanca",
    deliveryFeeMad: 100,
  },
  {
    id: "loc-hotel",
    name: "Hotel Delivery (Morocco)",
    nameFr: "Livraison hôtel",
    nameAr: "توصيل الفندق",
    type: "hotel",
    city: "Nationwide",
    deliveryFeeMad: 300,
  },
];

export const ADDONS: Addon[] = [
  {
    id: "gps",
    name: "GPS Navigation",
    nameFr: "GPS Navigation",
    description: "Turn-by-turn navigation across Morocco",
    dailyRateMad: 50,
  },
  {
    id: "child_seat",
    name: "Child Seat",
    nameFr: "Siège enfant",
    description: "EU-standard child safety seat",
    dailyRateMad: 40,
  },
  {
    id: "additional_driver",
    name: "Additional Driver",
    nameFr: "Conducteur supplémentaire",
    description: "Register a second authorized driver",
    dailyRateMad: 0,
    flatFeeMad: 150,
  },
  {
    id: "full_insurance",
    name: "Full Coverage Insurance",
    nameFr: "Assurance tous risques",
    description: "Zero excess / full CDW coverage",
    dailyRateMad: 120,
  },
];

export const CARS: Car[] = [
  {
    id: "car-001",
    make: "Dacia",
    model: "Logan",
    year: 2024,
    licensePlate: "60-A-12345",
    category: "economy",
    transmission: "manual",
    fuelType: "diesel",
    seats: 5,
    bags: 2,
    dailyRateMad: 250,
    status: "available",
    imageUrl:
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80",
    features: ["A/C", "Bluetooth", "USB"],
    description: "Reliable and fuel-efficient for city trips and short getaways.",
  },
  {
    id: "car-002",
    make: "Renault",
    model: "Clio",
    year: 2024,
    licensePlate: "60-B-23456",
    category: "economy",
    transmission: "automatic",
    fuelType: "essence",
    seats: 5,
    bags: 2,
    dailyRateMad: 320,
    status: "available",
    imageUrl:
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80",
    features: ["A/C", "Bluetooth", "Cruise Control", "Parking Sensors"],
    description: "Compact automatic — ideal for tourists exploring medinas and coasts.",
  },
  {
    id: "car-003",
    make: "Peugeot",
    model: "3008",
    year: 2023,
    licensePlate: "60-C-34567",
    category: "suv",
    transmission: "automatic",
    fuelType: "diesel",
    seats: 5,
    bags: 4,
    dailyRateMad: 550,
    status: "available",
    imageUrl:
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80",
    features: ["A/C", "GPS Ready", "Panoramic Roof", "Apple CarPlay"],
    description: "Spacious SUV for Atlas mountain roads and family travel.",
  },
  {
    id: "car-004",
    make: "Toyota",
    model: "RAV4",
    year: 2024,
    licensePlate: "60-D-45678",
    category: "suv",
    transmission: "automatic",
    fuelType: "hybrid",
    seats: 5,
    bags: 4,
    dailyRateMad: 650,
    status: "rented",
    imageUrl:
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80",
    features: ["Hybrid", "A/C", "4WD Assist", "Safety Sense"],
    description: "Efficient hybrid SUV with confident handling on long routes.",
  },
  {
    id: "car-005",
    make: "Mercedes-Benz",
    model: "E-Class",
    year: 2023,
    licensePlate: "60-E-56789",
    category: "luxury",
    transmission: "automatic",
    fuelType: "diesel",
    seats: 5,
    bags: 3,
    dailyRateMad: 1200,
    status: "available",
    imageUrl:
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80",
    features: ["Leather", "Premium Sound", "Adaptive Cruise", "Ambient Light"],
    description: "Executive sedan for business trips and VIP airport transfers.",
  },
  {
    id: "car-006",
    make: "BMW",
    model: "X5",
    year: 2024,
    licensePlate: "60-F-67890",
    category: "luxury",
    transmission: "automatic",
    fuelType: "diesel",
    seats: 5,
    bags: 5,
    dailyRateMad: 1500,
    status: "available",
    imageUrl:
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80",
    features: ["Luxury Interior", "4WD", "Head-Up Display", "Harman Kardon"],
    description: "Flagship luxury SUV — prestige meets Moroccan adventure.",
  },
  {
    id: "car-007",
    make: "Range Rover",
    model: "Sport",
    year: 2023,
    licensePlate: "60-G-78901",
    category: "luxury",
    transmission: "automatic",
    fuelType: "diesel",
    seats: 5,
    bags: 5,
    dailyRateMad: 2200,
    status: "available",
    imageUrl:
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80",
    features: ["Premium Leather", "Air Suspension", "Meridian Sound", "Terrain Response"],
    description: "Ultimate luxury for desert escapes and coastal drives.",
  },
  {
    id: "car-008",
    make: "Hyundai",
    model: "Tucson",
    year: 2024,
    licensePlate: "60-H-89012",
    category: "suv",
    transmission: "automatic",
    fuelType: "essence",
    seats: 5,
    bags: 4,
    dailyRateMad: 480,
    status: "maintenance",
    imageUrl:
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80",
    features: ["A/C", "Camera", "Smart Key", "Lane Assist"],
    description: "Modern crossover with strong value for mid-range trips.",
  },
  {
    id: "car-009",
    make: "Volkswagen",
    model: "Transporter",
    year: 2022,
    licensePlate: "60-I-90123",
    category: "van",
    transmission: "manual",
    fuelType: "diesel",
    seats: 9,
    bags: 8,
    dailyRateMad: 700,
    status: "available",
    imageUrl:
      "https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=800&q=80",
    features: ["9 Seats", "A/C", "Large Boot", "USB Ports"],
    description: "Group van for tours, weddings, and multi-family travel.",
  },
];

/** Seed bookings spanning today ± a few days for admin calendar demo */
function daysFromNow(offset: number, hour = 10): string {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

export const BOOKINGS: Booking[] = [
  {
    id: "bk-001",
    reference: "LCD-A3K9M2X7",
    carId: "car-004",
    status: "picked_up",
    pickupLocationId: "loc-cmn",
    dropoffLocationId: "loc-cmn",
    pickupDatetime: daysFromNow(-2, 9),
    dropoffDatetime: daysFromNow(3, 18),
    addons: ["full_insurance", "gps"],
    client: {
      fullName: "Sarah Mitchell",
      phone: "+212661234567",
      email: "sarah.m@example.com",
      whatsappPreferred: true,
      licenseNumber: "UK-DL-998877",
      idDocument: "P1234567",
    },
    totalMad: 4550,
    createdAt: daysFromNow(-5),
    updatedAt: daysFromNow(-2),
  },
  {
    id: "bk-002",
    reference: "LCD-B7N4P1Q8",
    carId: "car-005",
    status: "confirmed",
    pickupLocationId: "loc-rak",
    dropoffLocationId: "loc-driouch",
    pickupDatetime: daysFromNow(0, 11),
    dropoffDatetime: daysFromNow(4, 11),
    addons: ["additional_driver"],
    client: {
      fullName: "Youssef Benali",
      phone: "+212670987654",
      email: "youssef.b@example.com",
      whatsappPreferred: true,
      licenseNumber: "MA-PERM-445566",
      idDocument: "BE123456",
    },
    totalMad: 4950,
    createdAt: daysFromNow(-3),
    updatedAt: daysFromNow(-1),
  },
  {
    id: "bk-003",
    reference: "LCD-C2R5S9T1",
    carId: "car-002",
    status: "pending",
    pickupLocationId: "loc-ndg",
    dropoffLocationId: "loc-ndg",
    pickupDatetime: daysFromNow(1, 14),
    dropoffDatetime: daysFromNow(5, 14),
    addons: ["child_seat"],
    client: {
      fullName: "Marie Dupont",
      phone: "+33612345678",
      email: "marie.d@example.com",
      whatsappPreferred: false,
      licenseNumber: "FR-12AB34567",
      idDocument: "12AB34567",
    },
    totalMad: 1440,
    createdAt: daysFromNow(-1),
    updatedAt: daysFromNow(-1),
  },
  {
    id: "bk-004",
    reference: "LCD-D8U3V6W2",
    carId: "car-006",
    status: "confirmed",
    pickupLocationId: "loc-hotel",
    dropoffLocationId: "loc-cmn",
    pickupDatetime: daysFromNow(0, 16),
    dropoffDatetime: daysFromNow(2, 10),
    addons: ["full_insurance", "gps", "additional_driver"],
    client: {
      fullName: "James Chen",
      phone: "+447911123456",
      email: "james.c@example.com",
      whatsappPreferred: true,
      licenseNumber: "UK-DL-112233",
      idDocument: "P9988776",
    },
    totalMad: 3750,
    createdAt: daysFromNow(-2),
    updatedAt: daysFromNow(0),
  },
  {
    id: "bk-005",
    reference: "LCD-E1X4Y7Z3",
    carId: "car-001",
    status: "completed",
    pickupLocationId: "loc-driouch",
    dropoffLocationId: "loc-driouch",
    pickupDatetime: daysFromNow(-7, 10),
    dropoffDatetime: daysFromNow(-4, 10),
    addons: [],
    client: {
      fullName: "Hassan Amrani",
      phone: "+212661112233",
      email: "hassan.a@example.com",
      whatsappPreferred: true,
      licenseNumber: "MA-PERM-778899",
      idDocument: "BK987654",
    },
    totalMad: 750,
    createdAt: daysFromNow(-10),
    updatedAt: daysFromNow(-4),
  },
  {
    id: "bk-006",
    reference: "LCD-F5A2B8C4",
    carId: "car-003",
    status: "pending",
    pickupLocationId: "loc-tng",
    dropoffLocationId: "loc-aga",
    pickupDatetime: daysFromNow(2, 9),
    dropoffDatetime: daysFromNow(8, 18),
    addons: ["gps", "full_insurance"],
    client: {
      fullName: "Elena Rossi",
      phone: "+393331234567",
      email: "elena.r@example.com",
      whatsappPreferred: true,
      licenseNumber: "IT-DL-556677",
      idDocument: "YA1234567",
    },
    totalMad: 4620,
    createdAt: daysFromNow(0),
    updatedAt: daysFromNow(0),
  },
];

export function getDashboardMetrics(bookings: Booking[]): DashboardMetrics {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const tomorrow = new Date(today);
  tomorrow.setDate(tomorrow.getDate() + 1);

  const isToday = (iso: string) => {
    const d = new Date(iso);
    return d >= today && d < tomorrow;
  };

  return {
    todayPickups: bookings.filter(
      (b) =>
        isToday(b.pickupDatetime) &&
        (b.status === "confirmed" || b.status === "pending")
    ).length,
    todayDropoffs: bookings.filter(
      (b) => isToday(b.dropoffDatetime) && b.status === "picked_up"
    ).length,
    activeRentals: bookings.filter((b) => b.status === "picked_up").length,
    pendingRequests: bookings.filter((b) => b.status === "pending").length,
    monthlyRevenueMad: bookings
      .filter((b) => b.status !== "cancelled")
      .reduce((sum, b) => sum + b.totalMad, 0),
  };
}
